config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "pages#index"

  resources :posts do
  	resources :postcomments
  end	

  resources :photos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :photos ,dependent: :destroy

end

app/models/concerns/postcomments.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :photo, PhotoUploader

	belongs_to :user
	belongs_to :category

	has_many :vote ,dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomments
	validates :title,:body, presence: true
	validates :title, length: { in: 3..10 }
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true
end

app/models/postcomments.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :postcomments
  has_many :photos

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :nickname,:email,:password,:password_confirmation, presence: true
  validates :nickname, length: { in: 2..15 }
  validates :nickname, length: { in: 6..20 }
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :divise_sign_up_params, if: :devise_controller?
	protect_from_forgery with: :exception

private

	def divise_sign_up_params
		devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :nickname, :avatar])
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@posts = Post.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!

	def index
		@photos = Photo.all	
	end

	def new
		@photo = Photo.new
	end

	def create
		params[:photo][:category_id]=params[:category_id]
		params[:photo][:user_id]=current_user.id
		@photo=Photo.create(photo_params)
		redirect_to photos_path
	end

	def update
		if @photo.update(photo_params)
      		redirect_to photos_path
    	else
      		render 'edit'
    	end
	end

	def destroy
		@photo.destroy
  		redirect_to photos_path
	end

private

	def photo_params
		params.require(:photo).permit(:user_id, :name, :category_id, :photo)
	end

	def photo_set
 		@photo = Photo.find(params[:id])
  		
  	end
end

app/controllers/postcomments_controller.rb
class PostcommentsController < ApplicationController
before_action :authenticate_user!

  def create
  	params[:postcomment][:post_id] = params[:post_id]
  	params[:postcomment][:user_id] = current_user.id
  	@comment = Postcomment.create(comment_params)
    if @comment.save
      redirect_to post_path(params[:post_id])
      else
        @comment.errors.full_messages.each do |msg|
          @msg = msg
      end
      flash[:notice] = "#{@msg}"
      redirect_to post_path(params[:post_id])
    end
  end

  def edit
  	
  	redirect_to post_path(params[:post_id])
  end

  def destroy
  	
  	redirect_to post_path(params[:post_id])
  end

private

	def comment_params
		params.require(:postcomment).permit(:post_id, :user_id, :comment)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
before_action :set_post, only:[:show, :edit, :update, :destroy]

  def show
    @comment = @post.postcomments
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = current_user.posts.build(post_params)
  	if @post.save
  		redirect_to root_path
  	else 
  	render 'new'	
  	end	
  		
  end

  def edit

  end

  def update
  	@post.update(post_params)
  	redirect_to root_path
  end

  def destroy
  	@post.destroy
  	redirect_to root_path
  end

private

	def post_params
		params.require(:post).permit(:user_id, :title, :body)
	end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<div class="header">
          <nav class="navbar navbar-default">
              <div class="agileits-logo">
                <h1><div class="navbar-brand"><%= link_to "Home" , root_path %></div></h1>
              </div>

            <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav navbar-right">
                                  
                  <li><a href="#news" class="scroll">News</a></li>
                  <li><%= link_to "Gallery", photos_path %></li>
                  <li><a href="#about" class="scroll">About</a></li>
                  <% if current_user.nil? %>
                    <li>
                      <%= link_to new_user_session_path do %>
                        <i class="glyphicon glyphicon-user"></i></span> Login
                        <% end %>
                    <li>
                      <% else %>
                    <li>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <i class="glyphicon glyphicon-log-out"></i></span> Logout
                        <% end %>
                    <li>
                  <% end %>
                </ul>

            </div>
          </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  	<%=render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
			<div class="right-conteiner">
		<%= link_to "Create New Post", new_post_path , class: "btn btn-default"%>
</div>

<div class="center-container">
<% @posts.each do |post| %>
	<div class="col-md-4 post text-center">
	
	<h1><%= link_to post.title , post_path(post.id)%></h1>
	<p>
		<%= image_tag post.user.avatar.url, width: 30, height: 30 %>
		Autor:<%= post.user.nickname %> <br>
		<p><%= sanitize(post.body) %></p>
		Creeated at:<%= post.created_at %> <br>
		Update at:<%= post.updated_at %> <br>
	</p>
	
	<% if current_user != nil and current_user.id == post.user_id %>
		<%= link_to "Edit", edit_post_path(post.id) %>
		<%= link_to "Delete", post_path(post.id), data: {confim: 'Are you sure?'}, method: :delete %>
	<% end %>
	</div>
<% end %>
</div>
	

app/views/photos/_form.html.erb
<p><%= f.label :category  %></p>
<%= select_tag "category_id", options_from_collection_for_select(Category.all, :id,:name) %>

<p><%= f.label :name %></p>
<%= f.text_field :name %><br/>

<p><%= f.label "Photo" %></p>
<%= f.file_field :photo %><br/>


<p><%= f.submit "Save" %></p>

app/views/photos/edit.html.erb
<%= form_for @photo, url: photos_path, method: :patch do |f|%>


<%= render 'photos/form' , f:f %>

<% end %>

app/views/photos/index.html.erb
<%= link_to "Upload new foto", new_photo_path , class: "btn btn-default"%>
<br>
<% if @photos == [] %>
	Photos ninchen
<% else %>
	<% @photos.each do |photo| %>
 	<%= image_tag photo.photo_url, whdth: 200, height: 200 %>
 	<p>Name<%= photo.name %></p>
 	<p>Category<%= photo.category.name %></p>
 	<p>User<%= photo.user.nickname %></p>
 	<p><% if current_user != nil and current_user.id == photo.user_id %>
 		<%= link_to "Edit", edit_photo_path(photo.id) %>
 		<%= link_to "Delete", photo_path(photo.id), data: {confim: 'Are you sure?'}, method: :delete %>
 	<% end %>
 	</p>
  	<% end %>
  <% end %> 

app/views/photos/new.html.erb
<%= form_for @photo, url: photos_path, validate: true do |f|%>


<%= render 'photos/form' , f:f %>

<% end %>

app/views/posts/_form.html.erb
	<p><%= f.label :title %></p>
	<%= f.text_field :title %><br/>

	<p><%= f.label :body %></p>
	<%= f.text_area :body, :class => "tinymce",:rows => 15, :cols => 30%><br/>
	<%= tinymce %>

	<p><%= f.submit "Save" %></p>

app/views/posts/edit.html.erb
<%= form_for :post, url: post_path, method: :patch do |f|%>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
<% end %>

<%= render 'posts/form' , f:f %>

<% end %>

app/views/posts/new.html.erb
<%= form_for @post, url: posts_path, validate: true do |f|%>


<%= render 'posts/form' , f:f %>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>
	Autor:<%= @post.user.nickname %> |
	Creeated at:<%= @post.created_at %> |
	Update at:<%= @post.updated_at %>
</p>
<p><%= sanitize(@post.body) %></p>


<%= form_for :postcomment ,url: post_postcomments_path(@post.id), method: :post do |f| %>
	
	<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>

	<p><%= f.label "Add your comment" %></p>
	<p><%= f.text_area :comment, cols: 5,rows: 5 %></p>
	<%= f.submit "Add Comment" %>
<% end %>	

<% @comment.each do |comment| %>
<hr>
<%= image_tag comment.user.avatar.url, width: 30, height: 30 %>
<p>User <b><%= comment.user.nickname %></b> say: </p>
<p><%= comment.comment %></p>
<% if current_user != nil and current_user.id == comment.user_id %>
		<%= link_to "Edit", edit_post_postcomment_path(comment.id) %>
		<%= link_to "Delete", post_postcomment_path(comment.id), data: {confim: 'Are you sure?'}, method: :delete %>
	<% end %>
<hr>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>